---
- name: Deploy Flask App to Remote VM
  hosts: flask_servers
  become: true

  vars:
    app_dir: /tmp/flask_app

  tasks:
    - name: Ensure required packages are installed
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - python3
        - python3-pip
        - docker.io
        - docker-compose   # install docker-compose from apt instead of pip

    - name: Create app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'

    - name: Copy project files to remote VM
      copy:
        src: ./   # local project folder (Jenkins will copy from repo workspace)
        dest: "{{ app_dir }}"
        owner: "{{ ansible_user | default('devops-labs') }}"
        group: "{{ ansible_user | default('devops-labs') }}"
        mode: '0755'

    - name: Build Docker image on remote VM
      command: docker build -t flask-jenkins-app:latest .
      args:
        chdir: "{{ app_dir }}"

    - name: Stop old container if running
      command: docker rm -f flask-container
      ignore_errors: yes

    - name: Run Flask container
      command: docker run -d --name flask-container -p 5000:5000 flask-jenkins-app:latest
