---
- name: Deploy Flask App to Remote VM
  hosts: flask_servers
  become: true

  vars:
    app_dir: /tmp/flask_app

  tasks:
    - name: Ensure Python3, pip, and Docker are installed
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - python3
        - python3-pip
        - docker.io

    - name: Install docker-compose if needed
      pip:
        name: docker-compose

    - name: Create app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'

    - name: Copy project files to remote VM
      copy:
        src: ./   # make sure this folder contains your Flask app code
        dest: "{{ app_dir }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Copy Dockerfile explicitly
      copy:
        src: ./Dockerfile
        dest: "{{ app_dir }}/Dockerfile"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Build Docker image on remote VM
      command: docker build -t flask-jenkins-app:latest -f Dockerfile .
      args:
        chdir: "{{ app_dir }}"

    - name: Stop old container if running
      command: docker rm -f flask-container
      ignore_errors: yes

    - name: Run Flask container
      command: docker run -d --name flask-container -p 5000:5000 flask-jenkins-app:latest
